services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - db1
      - db2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStringMG=Host=db1;Port=5432;Database=pfs-mg;Username=postgres;Password=postgres
      - ConnectionStringsCore=Host=db2;Port=5432;Database=pfs-core;Username=postgres;Password=postgres
    ports:
      - "5000:80"
  db1:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pfs-mg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./DB-Dump/init-db1.sql:/docker-entrypoint-initdb.d/init-db1.sql
  db2:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pfs-core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./DB-Dump/init-db2.sql:/docker-entrypoint-initdb.d/init-db2.sql
volumes:
  db1_data:
  db2_data:

